apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade
resources:
  - namespace.yaml
  - https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml

