apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn
spec:
  secretName: longhorn-tls
  dnsNames:
    - longhorn-frontend.longhorn-system.svc.cluster.local
  issuerRef:
    name: self-issuer
    kind: ClusterIssuer