apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-medias
spec:
  interval: 60m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
        namespace: nfs-provisioner
  valuesFrom:
    - kind: Secret
      name: nfs-medias-values
