apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfs-provisioner
resources:
  - namespace.yaml
  - repository.yaml
  - helm-release.yaml
secretGenerator:
  - name: nfs-medias-values
    files: 
    - values.yaml=nfs-medias-values.enc.yaml
configurations:
  - "kustomizeconfig.yaml"

    