---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfs-provisioner
spec:
  interval: 60m0s
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/ 