domain: ENC[AES256_GCM,data:nzy25c6WPyNg3BQ=,iv:fGkq8JMDhm9qEofxlDc2p/xusFgke2zYHesYDGqNsiU=,tag:vR1dX3aWfQWfOUipOzURQQ==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:YGYtn8U=,iv:yxtvJeuAu88ihH8v9uKX8Z5OUStAmeic179iDdaGT0w=,tag:MPwiBWUS2SZcssFhVv9W4g==,type:bool]
pod:
    env:
        - name: ENC[AES256_GCM,data:NUg=,iv:FuzIQ0b1wdxqnTpvA88Br3wirI5kMPug7XbJXPIgfaM=,tag:q5wI4VCMIjg81aeVBLPg0A==,type:str]
          value: ENC[AES256_GCM,data:N5/aiQq8ufPbJgY4,iv:roG4dql0aaE6VA7kMG1PshzedOwzpbPxFrJGOyDtOvY=,tag:wr15hm/wzLkAPgWp6GZmLA==,type:str]
    resources:
        limits:
            cpu: ENC[AES256_GCM,data:qznBog==,iv:K4cknsTeaKVhHSzbmblQmczQK++3VBP4pFbAKXmcOTI=,tag:o/SYirJzWwPXgsyykZnQSA==,type:str]
            memory: ENC[AES256_GCM,data:xXoAv7c=,iv:IYCSOP+vTY+xk6dh5dAJr7oQYgFLp+hD5lVCHtEp8xw=,tag:uTJo8tVVwMNTWdSCgBZ4QA==,type:str]
        requests:
            cpu: ENC[AES256_GCM,data:mH2C,iv:PQ4AbRtn4tolNPux09ltPxzhMswNMM6KPIiDQAixY0U=,tag:BOPbMRGoA0Ik1lux5E8a0Q==,type:str]
            memory: ENC[AES256_GCM,data:wzncfA==,iv:F2wZLYSbEznc+P2jfxidy0zJ5RoBknyVVaert8Bdp0k=,tag:0AMBBMVU18AV2Kap4FPwqA==,type:str]
configMap:
    enabled: ENC[AES256_GCM,data:5X/n7Q==,iv:T49V0b08ub1Vh39duhyFd35i+HA/hBO/mUlUEPiLv1g=,tag:W3UGjIGc+hMQ2yRezlqVIw==,type:bool]
    key: ENC[AES256_GCM,data:1dydo2yskwFdqHqMDlvZBstD,iv:lCWS4NHHk2cwsfeBEsWImNE+a55lTGmlANEczQBnAbc=,tag:77SzBgw84Ho7NIKEjzxhsg==,type:str]
    default_2fa_method: ENC[AES256_GCM,data:6RORBcH3ZMM=,iv:XppLsihhWSLkisSCESJhZZf0nmJ28/6kx7qd6jNSraA=,tag:M53XdNDk6EcGVYgAfgt/bw==,type:str]
    authentication_backend:
        ldap:
            implementation: ENC[AES256_GCM,data:PeGysFsn,iv:q5fjbUSk28Cnk6mdkCVd1RRUObJZPE+eQcjQruta3AI=,tag:34fpcU2iIewUFZ9XoaqmaA==,type:str]
            url: ENC[AES256_GCM,data:+hbgOGXVSoiYh184zsACEcrUjGsLGs9AFliqfXcA/ZsFfT09oTK1XAxauWY=,iv:undakYMsFsyTUCgp1+WVRNKNwvATXWmZTKb/HWamVLc=,tag:v0ikEkOfFveWAG5ccdX2qg==,type:str]
            base_dn: ENC[AES256_GCM,data:4jhCMcCmmd86Yj5fW5jCeGOp,iv:oEHHqEludhm2f8rCICzLI2dhO3urgbsBlWi5ym2P73I=,tag:lcWpfdwlm2sv9/MDyA1LtA==,type:str]
            user: ENC[AES256_GCM,data:nMZ7FrugtyyL1mvlpuceVQt46LbS99u/H1/DcuXD,iv:44ctLDw9D6CWdiKKpoz0VMEYT42xfl4pMzichNu8Kf0=,tag:3SAv2GocMF9Nv+R+7S+jkg==,type:str]
            username_attribute: ENC[AES256_GCM,data:IHGi,iv:xZZUMyEBZRPDctr0O91HYNXegFYUHSyndNgd091K4NE=,tag:6wj1+og0u+Wkp8JZ6BTAgA==,type:str]
            group_name_attribute: ENC[AES256_GCM,data:ZPY=,iv:mP4rCyOTZJ5thNIKD8J1gBAVyeQmkIxSrInBbczJEik=,tag:9HfmUf4QWwNYdCra5bc9Pw==,type:str]
            mail_attribute: ENC[AES256_GCM,data:HH7DzQ==,iv:pz56e5ywr1heqC5XCXrjOss5mVy47YjdEClsOiIeLrQ=,tag:R20cr59wVCCHzPTE4Wc2/w==,type:str]
            additional_groups_dn: ENC[AES256_GCM,data:oj7p0mfR/GY=,iv:7TnLLivatlKKf6aCnkdqBGShS44/atUwKpIdknKqfrA=,tag:CxG+bcmOTTGXubzgNSBp4w==,type:str]
            additional_users_dn: ENC[AES256_GCM,data:umk80WUk+Uo=,iv:Ch1ByOgoNTsTGU0844NWAGClYO9XlkDGxb4/++1TlQI=,tag:2s3hGWIvXa3RzOd1LlzYhQ==,type:str]
            users_filter: ENC[AES256_GCM,data:IB/Ysuxb9uzqLlxoBlN7fUuGAC99MJ2spig1xkjFvQNy1ZNUx5AYpQ7LoZ+W5RBy3V3ahsNDTl54XvsCsfQQvV3vZiytE92DYqUGcE8vmRXKYG3YwygxiYM=,iv:VOXgaRm7FNfZ9Lcx+TvwZ4Aj0frCTl8FkB+zDrdYllc=,tag:U1FRqiyJLjA9bPHxwiXucw==,type:str]
            groups_filter: ENC[AES256_GCM,data:b3GE848CVTmKpiezj9+kUh7/w+hI3hJCku/F/E7UkFjsievO00FPRjbDjEIXgl8r,iv:fFX9PHZOTwcnRucXCJ5CrVeYhc5W57LrMReAyeLEPUo=,tag:8oURb7kyFE4ePf01nMnsPg==,type:str]
            tls:
                skip_verify: ENC[AES256_GCM,data:xphRmA==,iv:Kc8+c2AsSXLYZWJFxwBrmfL7eVHZSDq8vkf8KUoYwQY=,tag:hq8TDe7b8Z/HiycgXBXF8A==,type:bool]
    access_control:
        default_policy: ENC[AES256_GCM,data:+YqBdA==,iv:EJ7MQyBlmOzxuaYjz+xG9w6gRAvTnpOAHdeSI+KkLaU=,tag:1LR6f3kqZvj2LR9xYOfrdQ==,type:str]
        networks:
            - name: ENC[AES256_GCM,data:yILKvcv4C6w=,iv:lKPRKV0XHPaQk6VnqiPJOpaakJf2auk4AFtdIVltSnE=,tag:/TgD92cxbEyAf3tKMl2EcQ==,type:str]
              networks:
                - ENC[AES256_GCM,data:934QkCJwN05uDg==,iv:ACjgsQ0dukkJHhbNiTkGQFD56ZBYeS+JNtknSnXxDBA=,tag:9Yy33uofw0G0K0O7reKz+Q==,type:str]
                - ENC[AES256_GCM,data:fb2nbZYzLVwtd4/iSg==,iv:YkjLNCVN1Zpr6fhmU/G+dCHluw+/q16GKHN9q7RPF+E=,tag:TI9uSndmNNiZpEfPDTUpsw==,type:str]
                - ENC[AES256_GCM,data:TSS8ZkHVorP3n8gFTzE=,iv:QXef6MLHiMC5EyVu7Sw39d+pxWMdU/KNCJQ9maR9ovc=,tag:00/Mpe5cB030ASkWye75TA==,type:str]
        rules:
            - domain: ENC[AES256_GCM,data:0t6NEtIsM/WeNTrpFQ==,iv:WnHKF2jS2vxudR9hIQXlSkptqhqdrCGC6kdpQEKA+9o=,tag:zw9mw3QOXawTfgsE1h/kog==,type:str]
              policy: ENC[AES256_GCM,data:ED5rN6rTGw6yHQ==,iv:a11Gw4mRTrq+3xc/bR5GQHz5DJtZWu8XsziKrduanGI=,tag:zJOgA2sAaXYgsQeevDZ1OA==,type:str]
            - domain: ENC[AES256_GCM,data:kibiKFIwEKpt719sTg==,iv:w+KGOkYax/dE6KXFdvCum2CyMlRJsqFNKEizA704Mcw=,tag:1L2csRkyoNAbTQnlwmWnog==,type:str]
              policy: ENC[AES256_GCM,data:C4YMoGXY,iv:eEk7moOzNnw1BDNpoS72SowxBiiCCghp57qBVC8LuRE=,tag:iblux3lP0/ndzlDByK3UOQ==,type:str]
              networks:
                - ENC[AES256_GCM,data:bQ3V6JEuBu0=,iv:++2JwrtWvyZ9qAQhnhZ7rkQ5eYZTdQi5F1x/sDcp/8M=,tag:3eU+UcuNLj/Za6Fup3NBVw==,type:str]
    session:
        redis:
            enabled: ENC[AES256_GCM,data:+36DSA==,iv:sqO8oZkUj54uMqTOUcoiL/KR2ADgxLEyDHoUmDeFywE=,tag:CvaghBLCR8Ndvxfznnl+SA==,type:bool]
            enabledSecret: ENC[AES256_GCM,data:i/uIMA==,iv:FNT4VpgT7ecofeAKwsQYy93P19p9CR2hXrwvECGMZV8=,tag:lgmNYzcVVsguny/f5x/8Cw==,type:bool]
            host: ENC[AES256_GCM,data:/CtPWhw0jU0I2tGc2LFR+Sjd5KX/vmFDqsczY0qcOh4uSw==,iv:Tv02zjk0VgI4fdfhvmybmpMabcnWPgkFboeHmcypESM=,tag:MQ3ovPG3pvEE0X+PrWYwHA==,type:str]
            port: ENC[AES256_GCM,data:zam3Fw==,iv:Jf3Py4lt/1+ch1mCBX+R5iy4yWBFQIijU3oU81as7P8=,tag:X2hpavy3U7YmmV4JEAwY9g==,type:int]
            tls:
                enabled: ENC[AES256_GCM,data:mN+Eduk=,iv:o6PwDf5grxIS0hNcS9FhU+9VoXqJN03BB3/VeIajfkY=,tag:7ZV+gwFp/dyBDMKoWiO20w==,type:bool]
                server_name: ENC[AES256_GCM,data:3H0LHhRNS2oW3yf6lSoZ6pD17KrHDHR02mtpAkOe/oSCzA==,iv:wYOpYv1Gq+aKdPmjrap+SNqextWjydvF88JtV5Sj/7M=,tag:SkGhTg+wrH9ga4Rf/klf8Q==,type:str]
                skip_verify: ENC[AES256_GCM,data:qXtGIg==,iv:5+LTIs+TtraYFzo67JZphgEuMZQOAPyDeknQfMLFhkI=,tag:XGwgBa5/RptwquZGWSKQ1g==,type:bool]
    storage:
        postgres:
            enabled: ENC[AES256_GCM,data:A/Uq7g==,iv:lEz6+wN48HWnUdWco8JyL53wLg6bL8fMAkm+3QxMpxs=,tag:7WgxwrPuW4EtDaoqQQduew==,type:bool]
            host: ENC[AES256_GCM,data:ywVFOykBdU68/50WkE/lD5lfIbhekKErifJsGGQymyLoylznTfOEVaTEr7lOy2Q=,iv:4yePod3MSvSPhYq3QilmJGnvf79kCIfkyGKc1wytHPY=,tag:ZYSuituu2NnDnmK89mFt1g==,type:str]
            port: ENC[AES256_GCM,data:U52LHg==,iv:x3MHPgIr9tcZSdgULQJs88ZzEqHKt/Tpfpv+5gZwHig=,tag:2Sq1ziq8TvFKGPZcDh1m3A==,type:int]
            database: ENC[AES256_GCM,data:Qg0hMrJSB3g=,iv:FR+TaAAy6zzok+ab88i8CzCidmdgF0edyMGr47zsY/M=,tag:JtCjkjbFj5CWkVT1vShX8A==,type:str]
            schema: ENC[AES256_GCM,data:/MlzKf9h,iv:m2cnVQZ3XnZ6L6xhx2annIuXTn+fp4eHkoTwKQ8Kk4w=,tag:UZgrawGo9sydNfKMjAIQUA==,type:str]
            username: ENC[AES256_GCM,data:2NkMO2PE8C4=,iv:hsBKb1fJ9VgbwRiAL3oZitXm+1k1afE9+HFPEO5ok0Q=,tag:wguiYdc34SnQ+CRIqLrySA==,type:str]
            timeout: ENC[AES256_GCM,data:ykc=,iv:seABiUpZQJH8gHw0AeCdGVyPMoB5LPMuxIJ652IsZWQ=,tag:9KvmoBfUP1EC2nP8XIgf0g==,type:str]
        mysql:
            enabled: ENC[AES256_GCM,data:R55nflQ=,iv:bFkAdAYQkTV3Xw9DouZSXJlIsAV9CmRhjAMM+mrhr+8=,tag:Z5tOxHiN3uh+ISpmAjbrLA==,type:bool]
    notifier:
        smtp:
            enabledSecret: ENC[AES256_GCM,data:WAQapw==,iv:sbtO6yyujPP0/P6XbSelmrcwYxNANDgAXv1Bm6RpvCs=,tag:PBiXuPg23nXNowao9rHtkA==,type:bool]
            host: ENC[AES256_GCM,data:gwyN/2UYSquM1x1NL04=,iv:uPWAx7KLFwUOG7t+pCLVWH2mgG+QhhBQ37CT1R8YQlI=,tag:u4hxRwg4jEZb0/yg98HWlA==,type:str]
            port: ENC[AES256_GCM,data:uXbR,iv:VzszJLnZgQ9bwXl8yvEciZFblbMBrm91L0vboW8ytiQ=,tag:h8nGibJNtrVoj6IN85wLLw==,type:int]
            timeout: ENC[AES256_GCM,data:w74=,iv:i3fZuIg3J/2CjuHJaYyABCI7O3leL9/wFdC5PgQKReE=,tag:Eief4gFmCCzV9qyNkZLCIw==,type:str]
            username: ENC[AES256_GCM,data:u0YAi5mTc0UWT4IckIkAOUScJls=,iv:z70OW9hb0ZQ5ivYgwX8pux4tZsPcijLZeVNwL9VD9ZE=,tag:6UBmVy9nqifIC+z84U6Ftw==,type:str]
            sender: ENC[AES256_GCM,data:7JCcLLVVPeQh98XjD5ItHJQ0RWc=,iv:pKkq+bsik5tydDneytxEQrzcV/wq4HtoqiPQaF4FpV4=,tag:eCCHuvzE0wlGy7AB5GtP/A==,type:str]
            startup_check_address: ENC[AES256_GCM,data:dhOs2w3M/XqXyqixIwJdxOB4E/c=,iv:FFoVG14ruRxcqyY+qpFQoD97KKAJkq6EDcgKV+zc6lc=,tag:q2xaBMKwzYCKbJA/HIXXVg==,type:str]
            subject: ENC[AES256_GCM,data:NmXZg1e5I6oLdiVdu/pBgm7T,iv:vRmeC1+BPRfcQkI5lmIju1jhU2rVkL4QsEQHEFM7GsQ=,tag:bZ3dT5swEUTu/UuyXdTqkQ==,type:str]
secret:
    existingSecret: ENC[AES256_GCM,data:3psqDERlA3s=,iv:nT2j+ymaXvHXaIgALIB6qNG4RBXrm0yGfJpPUFTbocc=,tag:jWqQ/CyKjH9AkC1eZUbmLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-03T18:56:17Z"
    mac: ENC[AES256_GCM,data:yWQGapf7q9zjwWBwv7np6GqD9qDxToBCHZMfWRz7g4kI0+JeyfxN3GoSkRayFhFZJ775G7OYbPiUy1ihmLeXBtPkqfqnm9BE3PpuQ8DO3Z8ZXJIIZz791sYWk8IKReLFIy6T/L/9+EgGe2sypzmGZKsI6FwOeyhV/vt003OAvyE=,iv:zVvYKZPiH8LWWVRirXn+aIFp9JitC5ZNT0Ez7ROa2cQ=,tag:Vs/327h27NgdkKA5C9Ew9w==,type:str]
    pgp:
        - created_at: "2023-09-03T18:56:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyyGYy7YCFAQARAAsVUFjcp7s3FvqeehqtTyiydJ4RhFNzA5bOlRmSJ9Nx+W
            CywIASAKPmvsu1F5gtWD9rpce5OMWu7J0O1Rc223jAHKpHKVAMObbQOvHbpIoIjg
            jTx/zuPEaf23UCHhkV9285deCINF25L4rSmaexVQdvKT0EzplPe2u3oFvFI9OOVr
            7eDII1Pi3VqPgYfmg3QhMYuJ4C0TGCXStDyP3NuW5Bcr5w4PJX787d08CI+epl0m
            r8YQy7KmUzL+t9rjCKHDkF2eXLIMJJ9EG5B071D0rBsydxBYwpxMh0N3d/HdWqQJ
            m2MSVrsXouoWdnI2mP7nr5bKWNo3YgkdP1nejK8GyX6kvDutNlUtk7yUMcQ0cDTy
            hRHD4/3JGXtjByvPfwYGgEkFckQaJBsbDYq8yQiYDA1sCXbIhIgU77qkyhQI8iy6
            /cxkesqFKpHoPs9Pji7SK/aeeFziu5Dgl0AO6I8vVAlmXszaiUR8ViVhAciL5qaq
            LTUjVkD3Ue5AxRzyRkWWcInW9Hc6Ajc4kFSWRglfJ2mcCuFsOE1BgtcSKGhw3HQd
            uFrnLnlLnIkNzd08j7WHMnUtqVxj08JUcCTjF0wllGByrD/LZhQhykkZWmVKt010
            Cv7HmyzcH+L8ZwJEDqHl8wE4tmVBcTaIs8OO2jUYmE9dx5/vz6YsQ9TupENx9CbU
            aAEJAhCQXB65AmbDRToN/GIGsu8sLx8JEzgW0nUx3OBlRr6emRJ2ytcJVkmOA1aa
            TvKfSfDpE8do4NeVdVh9wEug6KKY4B4iltrHrJ4H4GZ/b3Vfb5O/T/NF6V2ZwXpa
            2dzXXXPOVu1g
            =qwP+
            -----END PGP MESSAGE-----
          fp: 75C3F62D6A9AA2165875F5C680A364E41D3C47AF
    unencrypted_suffix: _unencrypted
    version: 3.7.3
