apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - namespace.yaml
  - authelia-secrets.yaml
  - ingress.yaml
  - repository.yaml
  - release.yaml
secretGenerator:
  - name: authelia-values
    files: 
    - values.yaml=authelia-values.yaml
configurations:
  - "kustomizeconfig.yaml"