apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap
spec:
  secretName: ldap-tls
  dnsNames:
    - openldap.ldap.svc.cluster.local
  issuerRef:
    name: self-issuer
    kind: ClusterIssuer