apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ldap
resources:
  - namespace.yaml
  - secrets.yaml
  - sts.yaml
  - service.yaml
  - cert.yaml
configMapGenerator:
  - name: ldap-env
    envs:
      - .env
commonLabels:
  app: openldap