apiVersion: v1
data:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:deBmDZrt5htcFHtC5M/MKCRlLMEWkmlK5FB79A==,iv:cRCY9aT8l4hc0kT+XmHqwoFaFV9FNbYg2j02na1hAKQ=,tag:HAM7h3Q/M/UIytEiXN8rjA==,type:str]
    LDAP_ADMIN_USERNAME: ENC[AES256_GCM,data:fc/8+CVSrDIF/h5D,iv:VR3UfSXjcB5fGk2u9Q4+uvLEr4bNAMFS2OeL00dbHHQ=,tag:wZKVkkJB+m9wA8x5fSdUgw==,type:str]
    LDAP_PASSWORDS: ENC[AES256_GCM,data:7Oz2fIs0R3glbjTzc9M3T26Z8yWOZktOf+bheOiaETZMqr2938iQMUO+LhUUbWuSeH6GK2xGTjui0oMA,iv:spkXmEKHOA8S8323/RQZM+Ca0eUEc1CNVT+BSc8Wt9o=,tag:9Tmu9h3e3tC+TQxHpTveIA==,type:str]
    LDAP_ROOT: ENC[AES256_GCM,data:pccZ7bpVFTveS9zyKL8OTV12gy6c775y,iv:jpYrasn2/I7XkN++Yp6e4JxlUV5Jvx2Q65RSJDhE4bU=,tag:MXWESKzQw6C1WzvO34Pn6Q==,type:str]
    LDAP_USERS: ENC[AES256_GCM,data:RnHnxYXGzTCopYfDR9vBA5+EF2N+NvU9,iv:cCfyLP5u9lFBBJr5LBbaiXgaLkoakvfg2jXi7hGC27g=,tag:Zz1eEq+AmhsIsiyr+CoVrQ==,type:str]
kind: Secret
metadata:
    name: openldap-secrets
    namespace: ldap
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-03T18:23:35Z"
    mac: ENC[AES256_GCM,data:In7VzJFgE1MPBkP+zkmezwi1zBQAPTgi2uTehrilTTA7tU84Z4/CuBa/iFSYht6Bkz0VlmQQ2n/lIUwqyjbDdWIIwW1GqQL+PWnCGkdc+QXgldRqpEBjq31K3R1JeaZ0KZjhTktZpb46fzgSS87jDXMT9KW2t9+KbMEOWQiOze4=,iv:LKwznPuI2mofVij1POC7O2ENuBI8vn+g3inOabiVgYs=,tag:I5IJPaxTwh6adNOvqhy0+Q==,type:str]
    pgp:
        - created_at: "2023-09-03T18:23:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyyGYy7YCFAQARAAiQpn5lELRJQpyp5cM0vOlLcnnku2rvSjRGdQAYKEHWnS
            jF9WdJ7mgQO8uGLRc44N3k6gedS0k4WtuUeoopBBwGtNbmGLfkNYeOnyBALMGH20
            fBHtbzc7xs2vGn/82cfF3Mt4XV0oqUeDgQPxtwzk0sW51+8C3tQeAA9rin4w0Vwf
            OpVtVvI2JDFtMWLmSAmB139PMbTci7WoGrccdvIqf0BMsB+RnNs5HGWKbDEzzQL/
            deSxZc7hD8wnH3qSHwupJGB7LjLISQFvAib/H0WnC4xP8cHgYCHhVQwilynorKkk
            o5QvNNIauZFeG6SZ3TeNIZAEjA+gOI6U/taWXkIsqHPq75PF8xMd9CfaZ4WMmdXR
            0rggSRDdkV7evHEXUp+nx0AQaW2kW/PhPDPJ4L5LPTvyr6vgnO5dfaw6Vx3tChGk
            IJ98qsjp++zIl5mC0uIjhuArnx+9YrC9XBbe5GYbqVNYO1i8eJVFbxJd2g68IrQ7
            raKcmf3t2JvLZsCPwDWZ74dLH8+JdsYpmJUAe1h0jYlZx1A5yyecuTX6kk2Fsg2H
            0tr47l53dcffRBcTcFn3ct2YsCloMZko51/GJlUDHTTrk6f0t0L3ylS/HXhWHA1G
            euIjMg4GD5CDX+VmM2bgtDdBdPIwFDUyvwGB/S+kSMjd0TDJfyXTwhFis5lBdzbU
            aAEJAhBch+6BiRFv358CvFgOp0L22Kcfs4JnsfPH9yugeYZxFS0KVairvAzfHvnO
            qUH+K9MkNhRFk/ZqSRc/aHpcj9W5UtLEl5gGuK3m0rCTwxwLGnHosDZfqBkTYAV7
            21zZ4j87U4Yd
            =71Lw
            -----END PGP MESSAGE-----
          fp: 75C3F62D6A9AA2165875F5C680A364E41D3C47AF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
