apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfs-provisioner
resources:
  - helm-release.yaml
secretGenerator:
  - name: nfs-nextcloud-values
    files: 
    - values.yaml=nfs-nextcloud-values.yaml
