apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: ">=1.12.3"
  values:
    installCRDs: true
    replicaCount: 1
    extraArgs: 
      - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
      - --dns01-recursive-nameservers-only
    podDnsPolicy: None
    podDnsConfig: 
      nameservers:
        - 1.1.1.1
        - 9.9.9.9
  interval: 1h0m0s
  releaseName: cert-manager
  targetNamespace: cert-manager