apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: ">=2.10.4"
  values:
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
    logs:
      general:
        level: DEBUG
    deployment:
      replicas: 1
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
    ingressRoute:
      dashboard:
        enabled: false
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.10.200
  interval: 1h0m0s
  releaseName: traefik
  targetNamespace: traefik
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace

